immutable_features:
  - sex

sensitive_features:
  - sex

actionable_features:
  - credit_amount
  - duration
  - housing
  - saving_accounts
  - checking_account
  - job
  - purpose

continuous_features:
  - age
  - job
  - credit_amount
  - duration

categorical_features:
  - sex
  - housing
  - saving_accounts
  - checking_account
  - purpose

feature_ranges:
  credit_amount: [250, 20000]
  duration: [4, 72]